export const typesArray = [
  "Hostel",
  "Hotel",
  "Lodging",
  "Motel",
  "Resort",
  "Youth Hostel",
  "Buffet Restaurant",
  "Chinese Restaurant",
  "Coffee Shop",
  "Fast Food Restaurant",
  "Fish Restaurant",
  "Gluten Free Restaurant",
  "Indian Restaurant",
  "Italian Restaurant",
  "Japanese Restaurant",
  "Pizzeria",
  "Restaurant",
  "Steakhouse",
  "Vegetarian Restaurant",
  "Sunset Spot",
  "Windmill",
  "Watermill",
  "Waterfall",
  "Beach",
  "Hotspring",
  "Zoo",
  "Anthropology Museum",
  "Archeological Museum",
  "Art Museum",
  "Cinema",
  "Historical Museum",
  "Industry Museum",
  "Museum",
  "Monument",
  "Naval Museum",
  "Planetarium",
  "Science Museum",
  "Theater",
  "War Museum",
  "Agritourism",
  "Ancient Monument",
  "Arch",
  "Beautiful View",
  "Camping",
  "Castle",
  "Cathedral",
  "Cave",
  "City Square",
  "City Wall",
  "Ghost Town",
  "Historical Quarter",
  "Lighthouse",
  "Marina",
  "Megalith",
  "Memorial",
  "Modern Bridge",
  "Modern Tower",
  "Old Bridge",
  "Palace",
  "Panoramic View",
  "Park",
  "Petroglyph",
  "Picnic",
  "Ruin",
  "Statue",
  "Temple",
  "Tower",
  "Pharmacy",
  "Gas Station",
];
