// import {
//   AF,
//   AL,
//   DZ,
//   AD,
//   AO,
//   AG,
//   AR,
//   AM,
//   AU,
//   AT,
//   AZ,
//   BH,
//   BD,
//   BB,
//   BY,
//   BE,
//   BZ,
//   BJ,
//   BT,
//   BO,
//   BA,
//   BW,
//   BR,
//   BN,
//   BF,
//   BG,
//   BI,
//   KH,
//   CM,
//   CA,
//   CV,
//   CF,
//   TD,
//   CH,
//   CL,
//   CN,
//   CO,
//   CR,
//   KM,
//   CI,
//   CU,
//   CY,
//   CZ,
//   HR,
//   CD,
//   DK,
//   DJ,
//   DO,
//   DM,
//   EC,
//   EG,
//   SV,
//   GQ,
//   ER,
//   EE,
//   SZ,
//   ET,
//   FJ,
//   FI,
//   FR,
//   GA,
//   GE,
//   DE,
//   GH,
//   GR,
//   GD,
//   GT,
//   GW,
//   GY,
//   GN,
//   HT,
//   HN,
//   HU,
//   IS,
//   IN,
//   ID,
//   IR,
//   IQ,
//   IE,
//   IL,
//   IT,
//   JM,
//   JP,
//   JO,
//   KZ,
//   KE,
//   KI,
//   KW,
//   KG,
//   LA,
//   LV,
//   LB,
//   LS,
//   LR,
//   LY,
//   LI,
//   LT,
//   LU,
//   MG,
//   MW,
//   MY,
//   MV,
//   ML,
//   MT,
//   MH,
//   MR,
//   MU,
//   MX,
//   FM,
//   MD,
//   MC,
//   MN,
//   ME,
//   MA,
//   MZ,
//   MM,
//   NA,
//   NR,
//   NP,
//   NL,
//   NZ,
//   NI,
//   NE,
//   NG,
//   KP,
//   MK,
//   NO,
//   OM,
//   PK,
//   PW,
//   PA,
//   PG,
//   PY,
//   PE,
//   PH,
//   PL,
//   PT,
//   QA,
//   CG,
//   RO,
//   RU,
//   RW,
//   KN,
//   LC,
//   VC,
//   WS,
//   SM,
//   ST,
//   SA,
//   SN,
//   RS,
//   SC,
//   SL,
//   SG,
//   SK,
//   SI,
//   SB,
//   SO,
//   ZA,
//   KR,
//   SS,
//   ES,
//   LK,
//   SD,
//   SR,
//   SE,
//   SY,
//   TJ,
//   TZ,
//   TH,
//   BS,
//   GM,
//   TL,
//   TG,
//   TO,
//   TT,
//   TN,
//   TR,
//   TM,
//   TV,
//   UG,
//   UA,
//   AE,
//   US,
//   GB,
//   UY,
//   UZ,
//   VU,
//   VE,
//   VN,
//   YE,
//   ZM,
//   ZW,
// } from "country-flag-icons/react/3x2";

// export const countrys = [
//   { icon: <AF title="Afghanistan" />, name: "Afghanistan" },
//   { icon: <AL title="Albania" />, name: "Albania" },
//   { icon: <DZ title="Algeria" />, name: "Algeria" },
//   { icon: <AD title="Andorra" />, name: "Andorra" },
//   { icon: <AO title="Angola" />, name: "Angola" },
//   { icon: <AG title="Antigua and Barbuda" />, name: "Antigua and Barbuda" },
//   { icon: <AR title="Argentina" />, name: "Argentina" },
//   { icon: <AM title="Armenia" />, name: "Armenia" },
//   { icon: <AU title="Australia" />, name: "Australia" },
//   { icon: <AT title="Austria" />, name: "Austria" },
//   { icon: <AZ title="Azerbaijan" />, name: "Azerbaijan" },
//   { icon: <BH title="Bahrain" />, name: "Bahrain" },
//   { icon: <BD title="Bangladesh" />, name: "Bangladesh" },
//   { icon: <BB title="Barbados" />, name: "Barbados" },
//   { icon: <BY title="Belarus" />, name: "Belarus" },
//   { icon: <BE title="Belgium" />, name: "Belgium" },
//   { icon: <BZ title="Belize" />, name: "Belize" },
//   { icon: <BJ title="Benin" />, name: "Benin" },
//   { icon: <BT title="Bhutan" />, name: "Bhutan" },
//   { icon: <BO title="Bolivia" />, name: "Bolivia" },
//   {
//     icon: <BA title="Bosnia and Herzegovina" />,
//     name: "Bosnia and Herzegovina",
//   },
//   { icon: <BW title="Botswana" />, name: "Botswana" },
//   { icon: <BR title="Brazil" />, name: "Brazil" },
//   { icon: <BN title="Brunei" />, name: "Brunei" },
//   { icon: <BG title="Bulgaria" />, name: "Bulgaria" },
//   { icon: <BF title="Burkina Faso" />, name: "Burkina Faso" },
//   { icon: <BI title="Burundi" />, name: "Burundi" },
//   { icon: <KH title="Cambodia" />, name: "Cambodia" },
//   { icon: <CM title="Cameroon" />, name: "Cameroon" },
//   { icon: <CA title="Canada" />, name: "Canada" },
//   { icon: <CV title="Cape Verde" />, name: "Cape Verde" },
//   {
//     icon: <CF title="Central African Republic" />,
//     name: "Central African Republic",
//   },
//   { icon: <TD title="Chad" />, name: "Chad" },
//   { icon: <CL title="Chile" />, name: "Chile" },
//   { icon: <CN title="China" />, name: "China" },
//   { icon: <CO title="Colombia" />, name: "Colombia" },
//   { icon: <KM title="Comoros" />, name: "Comoros" },
//   { icon: <CR title="Costa Rica" />, name: "Costa Rica" },
//   { icon: <CI title="Côte d’Ivoire" />, name: "Côte d’Ivoire" },
//   { icon: <HR title="Croatia" />, name: "Croatia" },
//   { icon: <CU title="Cuba" />, name: "Cuba" },
//   { icon: <CY title="Cyprus" />, name: "Cyprus" },
//   { icon: <CZ title="Czechia" />, name: "Czechia" },
//   {
//     icon: <CD title="Democratic Republic of the Congo" />,
//     name: "Democratic Republic of the Congo",
//   },
//   { icon: <DK title="Denmark" />, name: "Denmark" },
//   { icon: <DJ title="Djibouti" />, name: "Djibouti" },
//   { icon: <DM title="Dominica" />, name: "Dominica" },
//   { icon: <DO title="Dominican Republic" />, name: "Dominican Republic" },
//   { icon: <EC title="Ecuador" />, name: "Ecuador" },
//   { icon: <EG title="Egypt" />, name: "Egypt" },
//   { icon: <SV title="El Salvador" />, name: "El Salvador" },
//   { icon: <GQ title="Equatorial Guinea" />, name: "Equatorial Guinea" },
//   { icon: <ER title="Eritrea" />, name: "Eritrea" },
//   { icon: <EE title="Estonia" />, name: "Estonia" },
//   { icon: <SZ title="Eswatini" />, name: "Eswatini" },
//   { icon: <ET title="Ethiopia" />, name: "Ethiopia" },
//   { icon: <FJ title="Fiji" />, name: "Fiji" },
//   { icon: <FI title="Finland" />, name: "Finland" },
//   { icon: <FR title="France" />, name: "France" },
//   { icon: <GA title="Gabon" />, name: "Gabon" },
//   { icon: <GE title="Georgia" />, name: "Georgia" },
//   { icon: <DE title="Germany" />, name: "Germany" },
//   { icon: <GH title="Ghana" />, name: "Ghana" },
//   { icon: <GR title="Greece" />, name: "Greece" },
//   { icon: <GD title="Grenada" />, name: "Grenada" },
//   { icon: <GT title="Guatemala" />, name: "Guatemala" },
//   { icon: <GN title="Guinea" />, name: "Guinea" },
//   { icon: <GW title="Guinea-Bissau" />, name: "Guinea-Bissau" },
//   { icon: <GY title="Guyana" />, name: "Guyana" },
//   { icon: <HT title="Haiti" />, name: "Haiti" },
//   { icon: <HN title="Honduras" />, name: "Honduras" },
//   { icon: <HU title="Hungary" />, name: "Hungary" },
//   { icon: <IS title="Iceland" />, name: "Iceland" },
//   { icon: <IN title="India" />, name: "India" },
//   { icon: <ID title="Indonesia" />, name: "Indonesia" },
//   { icon: <IR title="Iran" />, name: "Iran" },
//   { icon: <IQ title="Iraq" />, name: "Iraq" },
//   { icon: <IE title="Ireland" />, name: "Ireland" },
//   { icon: <IL title="Israel" />, name: "Israel" },
//   { icon: <IT title="Italy" />, name: "Italy" },
//   { icon: <JM title="Jamaica" />, name: "Jamaica" },
//   { icon: <JP title="Japan" />, name: "Japan" },
//   { icon: <JO title="Jordan" />, name: "Jordan" },
//   { icon: <KZ title="Kazakhstan" />, name: "Kazakhstan" },
//   { icon: <KE title="Kenya" />, name: "Kenya" },
//   { icon: <KI title="Kiribati" />, name: "Kiribati" },
//   { icon: <KW title="Kuwait" />, name: "Kuwait" },
//   { icon: <KG title="Kyrgyzstan" />, name: "Kyrgyzstan" },
//   { icon: <LA title="Laos" />, name: "Laos" },
//   { icon: <LV title="Latvia" />, name: "Latvia" },
//   { icon: <LB title="Lebanon" />, name: "Lebanon" },
//   { icon: <LS title="Lesotho" />, name: "Lesotho" },
//   { icon: <LR title="Liberia" />, name: "Liberia" },
//   { icon: <LY title="Libya" />, name: "Libya" },
//   { icon: <LI title="Liechtenstein" />, name: "Liechtenstein" },
//   { icon: <LT title="Lithuania" />, name: "Lithuania" },
//   { icon: <LU title="Luxembourg" />, name: "Luxembourg" },
//   { icon: <MG title="Madagascar" />, name: "Madagascar" },
//   { icon: <MW title="Malawi" />, name: "Malawi" },
//   { icon: <MY title="Malaysia" />, name: "Malaysia" },
//   { icon: <MV title="Maldives" />, name: "Maldives" },
//   { icon: <ML title="Mali" />, name: "Mali" },
//   { icon: <MT title="Malta" />, name: "Malta" },
//   { icon: <MH title="Marshall Islands" />, name: "Marshall Islands" },
//   { icon: <MR title="Mauritania" />, name: "Mauritania" },
//   { icon: <MU title="Mauritius" />, name: "Mauritius" },
//   { icon: <MX title="Mexico" />, name: "Mexico" },
//   {
//     icon: <FM title="Federated States of Micronesia" />,
//     name: "Federated States of Micronesia",
//   },
//   { icon: <MD title="Moldova" />, name: "Moldova" },
//   { icon: <MC title="Monaco" />, name: "Monaco" },
//   { icon: <MN title="Mongolia" />, name: "Mongolia" },
//   { icon: <ME title="Montenegro" />, name: "Montenegro" },
//   { icon: <MA title="Morocco" />, name: "Morocco" },
//   { icon: <MZ title="Mozambique" />, name: "Mozambique" },
//   { icon: <MM title="Myanmar (Burma)" />, name: "Myanmar (Burma)" },
//   { icon: <NA title="Namibia" />, name: "Namibia" },
//   { icon: <NR title="Nauru" />, name: "Nauru" },
//   { icon: <NP title="Nepal" />, name: "Nepal" },
//   { icon: <NL title="Netherlands" />, name: "Netherlands" },
//   { icon: <NZ title="New Zealand" />, name: "New Zealand" },
//   { icon: <NI title="Nicaragua" />, name: "Nicaragua" },
//   { icon: <NE title="Niger" />, name: "Niger" },
//   { icon: <NG title="Nigeria" />, name: "Nigeria" },
//   { icon: <KP title="North Korea" />, name: "North Korea" },
//   { icon: <MK title="North Macedonia" />, name: "North Macedonia" },
//   { icon: <NO title="Norway" />, name: "Norway" },
//   { icon: <OM title="Oman" />, name: "Oman" },
//   { icon: <PK title="Pakistan" />, name: "Pakistan" },
//   { icon: <PW title="Palau" />, name: "Palau" },
//   { icon: <PA title="Panama" />, name: "Panama" },
//   { icon: <PG title="Papua New Guinea" />, name: "Papua New Guinea" },
//   { icon: <PY title="Paraguay" />, name: "Paraguay" },
//   { icon: <PE title="Peru" />, name: "Peru" },
//   { icon: <PH title="Philippines" />, name: "Philippines" },
//   { icon: <PL title="Poland" />, name: "Poland" },
//   { icon: <PT title="Portugal" />, name: "Portugal" },
//   { icon: <QA title="Qatar" />, name: "Qatar" },
//   { icon: <CG title="Republic of the Congo" />, name: "Republic of the Congo" },
//   { icon: <RO title="Romania" />, name: "Romania" },
//   { icon: <RU title="Russia" />, name: "Russia" },
//   { icon: <RW title="Rwanda" />, name: "Rwanda" },
//   { icon: <KN title="St Kitts & Nevis" />, name: "St Kitts & Nevis" },
//   { icon: <LC title="St Lucia" />, name: "St Lucia" },
//   {
//     icon: <VC title="St Vincent and the Grenadines" />,
//     name: "St Vincent and the Grenadines",
//   },
//   { icon: <WS title="Samoa" />, name: "Samoa" },
//   { icon: <SM title="San Marino" />, name: "San Marino" },
//   { icon: <ST title="São Tomé and Príncipe" />, name: "São Tomé and Príncipe" },
//   { icon: <SA title="Saudi Arabia" />, name: "Saudi Arabia" },
//   { icon: <SN title="Senegal" />, name: "Senegal" },
//   { icon: <RS title="Serbia" />, name: "Serbia" },
//   { icon: <SC title="Seychelles" />, name: "Seychelles" },
//   { icon: <SL title="Sierra Leone" />, name: "Sierra Leone" },
//   { icon: <SG title="Singapore" />, name: "Singapore" },
//   { icon: <SK title="Slovakia" />, name: "Slovakia" },
//   { icon: <SI title="Slovenia" />, name: "Slovenia" },
//   { icon: <SB title="Solomon Islands" />, name: "Solomon Islands" },
//   { icon: <SO title="Somalia" />, name: "Somalia" },
//   { icon: <ZA title="South Africa" />, name: "South Africa" },
//   { icon: <KR title="South Korea" />, name: "South Korea" },
//   { icon: <SS title="South Sudan" />, name: "South Sudan" },
//   { icon: <ES title="Spain" />, name: "Spain" },
//   { icon: <LK title="Sri Lanka" />, name: "Sri Lanka" },
//   { icon: <SD title="Sudan" />, name: "Sudan" },
//   { icon: <SR title="Suriname" />, name: "Suriname" },
//   { icon: <SE title="Sweden" />, name: "Sweden" },
//   { icon: <CH title="Switzerland" />, name: "Switzerland" },
//   { icon: <SY title="Syria" />, name: "Syria" },
//   { icon: <TJ title="Tajikistan" />, name: "Tajikistan" },
//   { icon: <TZ title="Tanzania" />, name: "Tanzania" },
//   { icon: <TH title="Thailand" />, name: "Thailand" },
//   { icon: <BS title="The Bahamas" />, name: "The Bahamas" },
//   { icon: <GM title="The Gambia" />, name: "The Gambia" },
//   { icon: <TL title="Timor-Leste" />, name: "Timor-Leste" },
//   { icon: <TG title="Togo" />, name: "Togo" },
//   { icon: <TO title="Tonga" />, name: "Syria" },
//   { icon: <TT title="Trinidad and Tobago" />, name: "Trinidad and Tobago" },
//   { icon: <TN title="Tunisia" />, name: "Tunisia" },
//   { icon: <TR title="Turkey" />, name: "Turkey" },
//   { icon: <TM title="Turkmenistan" />, name: "Turkmenistan" },
//   { icon: <TV title="Tuvalu" />, name: "Tuvalu" },
//   { icon: <UG title="Uganda" />, name: "Uganda" },
//   { icon: <UA title="Ukraine" />, name: "Ukraine" },
//   { icon: <AE title="United Arab Emirates" />, name: "United Arab Emirates" },
//   { icon: <SY title="United Kingdom" />, name: "United Kingdom" },
//   { icon: <GB title="United States" />, name: "United States" },
//   { icon: <UY title="Uruguay" />, name: "Uruguay" },
//   { icon: <UZ title="Uzbekistan" />, name: "Uzbekistan" },
//   { icon: <VU title="Vanuatu" />, name: "Vanuatu" },
//   { icon: <VE title="Venezuela" />, name: "Venezuela" },
//   { icon: <VN title="Vietnam" />, name: "Vietnam" },
//   { icon: <YE title="Yemen" />, name: "Yemen" },
//   { icon: <ZM title="Zambia" />, name: "Zambia" },
//   { icon: <ZW title="Zimbabwe" />, name: "Zimbabwe" },
// ];
