export const unacceptedCountries = [
  "American Samoa",
  "Anguilla",
  "Antarctica",
  "Aruba",
  "Ascension Island",
  "Bermuda",
  "Bouvet Island",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Canary Islands",
  "Caribbean Netherlands",
  "Cayman Islands",
  "Ceuta & Melilla",
  "Christmas Island",
  "Clipperton Island",
  "Cocos Islands",
  "Cook Islands",
  "Curaçao",
  "Diego Garcia",
  "Falkland Islands",
  "Faroe Islands",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gibraltar",
  "Greenland",
  "Guadeloupe",
  "Guam",
  "Guernsey",
  "Hong Kong",
  "Heard & McDonald Islands",
  "Isle of Man",
  "Jersey",
  "Kosovo",
  "Macao",
  "Martinique",
  "Mayotte",
  "Montserrat",
  "New Caledonia",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Palestine",
  "Pitcairn Islands",
  "Puerto Rico",
  "Réunion",
  "Sint Maarten",
  "South Georgia & South Sandwich Islands",
  "St. Barthélemy",
  "St. Helena",
  "St. Martin",
  "St. Pierre & Miquelon",
  "Svalbard & Jan Mayen",
  "Taiwan",
  "Tokelau",
  "Tristan da Cunha",
  "Turks & Caicos Islands",
  "U.S. Outlying Islands",
  "U.S. Virgin Islands",
  "Vatican City",
  "Wallis & Futuna",
  "Western Sahara",
  "Åland Islands",
];
